name: Update Visits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-visits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment visit counter
        id: increment
        run: |
          if [ ! -f visits.txt ]; then echo "0" > visits.txt; fi
          visits=$(cat visits.txt)
          visits=$((visits + 1))
          echo $visits > visits.txt
          echo "::set-output name=visits::$visits"
  
      - name: Update README.md with badge
        run: |
          VISITS=$(cat visits.txt)
          BADGE="![Visits](https://img.shields.io/badge/Visits-$VISITS-blue?style=flat-square&logo=github)"
          sed -i "s|!\[Visits\](.*)|$BADGE|" README.md
  
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update visits badge'
          git push